version: 2.1

docker: &DOCKER_NODE
  docker:
    - image: cimg/node:18.7.0

slack_context: &SLACK_NOTIFICATION_CONTEXT
  context:
    - &SLACK_NOTIFICATION_CONTEXT_ENTRY FE Slack notifications

slack_notify: &SLACK_NOTIFY
  slack/notify:
    event: fail
    template: basic_fail_1
    branch_pattern: main

orbs:
  slack: circleci/slack@4.10.1

jobs:
  validate_renovate_config:
    <<: *DOCKER_NODE
    resource_class: small
    steps:
      - checkout
      - run: RENOVATE_CONFIG_FILE=default.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=pkg.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=web.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=internalSmgPackageUpdate.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=groupDevDependencies.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=autoMergeNonMajorNode.json npx -p renovate renovate-config-validator
      - run: RENOVATE_CONFIG_FILE=autoMergeNonMajorDocker.json npx -p renovate renovate-config-validator
      - <<: *SLACK_NOTIFY

workflows:
  test_and_release:
    jobs:
      - validate_renovate_config:
          <<: *SLACK_NOTIFICATION_CONTEXT
