version: 2.1

orbs:
  renovate: daniel-shuy/renovate@3.1.0

workflows:
  validate_config:
    jobs:
      - renovate/validate-self-hosted-config:
          renovate_version: $RENOVATE_VERSION
          self_hosted_config_file_path: default.json
